# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4c8ea9392e61d6533649a11c83b9c33ddeccc48fee8c22e47c4abdb3a0c629fa4e84b9ca91d6128d5cc41278b4d0f9e74afec1fc58b2960fc8b74b12a11ea1f

test:
  secret_key_base: e1cd651ee1297a088affb03f09b121b2dca76bd807600fff6b7d2ae772907c152cd39f708d7f210d3f0c69a3cb8509fc8cade39745fd84aadeb95af0b8fe1f6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
